import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GlobalQueryClientProvider } from '@/components/QueryClient'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <GlobalQueryClientProvider>
            <main className="flex w-full items-center justify-center">
              <div className="max-w-[1800px] w-full">{children}</div>
            </main>
          </GlobalQueryClientProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
