import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GlobalQueryClientProvider } from '@/components/QueryClient'
import { Toaster } from '@/components/ui/toaster'
import { getSession } from '@/utils/auth/session'
import SessionProvider from '@/components/SessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getSession()

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <GlobalQueryClientProvider>
            <Toaster />
            <SessionProvider session={session}>
              <main className="flex w-full items-center justify-center">
                <div className="max-w-[1800px] w-full">{children}</div>
              </main>
            </SessionProvider>
          </GlobalQueryClientProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
