import {
  Users,
  User,
  Folder,
  KeyRound,
  Settings,
  Book,
  Mic2,
  Code,
  LogOut,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Plus,
  Layers,
  XCircle,
  Menu,
  X,
  MoreHorizontal,
  MoreVertical,
  Trash,
  Webhook,
  Pencil,
  AlertCircle,
  EyeOff,
  Eye,
  Copy,
  Archive,
  Search,
  Undo,
  Save,
  FileText,
  FileJson,
  Inbox,
  SearchX,
  RefreshCcw,
  CheckCircle,
  CheckCircle2,
  Check,
  MessageCircle,
  MessageSquare,
  FileX,
  FilePlus,
  FilePlus2,
  SquareAsterisk,
  Lock,
  Unlock,
  Tag,
  PenSquare,
  ArrowUpWideNarrow,
  ArrowDownWideNarrow,
  Group,
  Upload,
} from 'lucide-react'

export const Icons = {
  user: User,
  users: Users,
  folder: Folder,
  keyRound: KeyRound,
  settings: Settings,
  book: Book,
  mic2: Mic2,
  code: Code,
  logOut: LogOut,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  plus: Plus,
  layer: Layers,
  xCircle: XCircle,
  menu: Menu,
  x: X,
  moreHorizontal: MoreHorizontal,
  trash: Trash,
  webhook: Webhook,
  pencil: Pencil,
  alertCircle: AlertCircle,
  moreVertical: MoreVertical,
  eye: Eye,
  eyeOff: EyeOff,
  copy: Copy,
  archive: Archive,
  search: Search,
  undo: Undo,
  save: Save,
  fileText: FileText,
  fileJson: FileJson,
  inbox: Inbox,
  searchX: SearchX,
  refresh: RefreshCcw,
  checkCircle: CheckCircle,
  checkCircle2: CheckCircle2,
  check: Check,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  fileX: FileX,
  filePlus: FilePlus,
  filePlus2: FilePlus2,
  squareAsterisk: SquareAsterisk,
  lock: Lock,
  unlock: Unlock,
  tag: Tag,
  penSquare: PenSquare,
  chevronUp: ChevronUp,
  arrowUpWideNarrow: ArrowUpWideNarrow,
  arrowDownWideNarrow: ArrowDownWideNarrow,
  group: Group,
  upload: Upload,
}
