import {
  Users,
  User,
  Folder,
  KeyRound,
  Settings,
  Book,
  Mic2,
  Code,
  LogOut,
  ChevronDown,
  ChevronRight,
  Plus,
  Layers,
  XCircle,
  Menu,
  X,
  MoreHorizontal,
  MoreVertical,
  Trash,
  Webhook,
  Pencil,
  AlertCircle,
  EyeOff,
  Eye,
  Copy,
  Archive,
  Search,
  Undo
} from 'lucide-react'

export const Icons = {
  user: User,
  users: Users,
  folder: Folder,
  keyRound: KeyRound,
  settings: Settings,
  book: Book,
  mic2: Mic2,
  code: Code,
  logOut: LogOut,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  plus: Plus,
  layer: Layers,
  xCircle: XCircle,
  menu: Menu,
  x: X,
  moreHorizontal: MoreHorizontal,
  trash: Trash,
  webhook: Webhook,
  pencil: Pencil,
  alertCircle: AlertCircle,
  moreVertical: MoreVertical,
  eye: Eye,
  eyeOff: EyeOff,
  copy: Copy,
  archive: Archive,
  search: Search,
  undo: Undo,
}
